In [ ]:
# Diabetes Prediction Using Logistic Regression

#This project uses binary logisstic regression to predict whether a
#person has diabetes using health related data.

In [29]:
from google.colab import files
uploaded = files.upload()

Saving diabetes.csv to diabetes (1).csv


In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

In [30]:
import pandas as pd

file_path="diabetes.csv"

df=pd.read_csv(file_path)

print("Dataset loaded successfully!")
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

Dataset loaded successfully!
Number of rows: 768
Number of columns: 9


In [31]:
print(df.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148           72.0             35    169.5  33.6   
1            1       85           66.0             29    102.5  26.6   
2            8      183           64.0             32    169.5  23.3   
3            1       89           66.0             23     94.0  28.1   
4            0      137           40.0             35    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  


In [28]:
print(df.columns)
print(df.info())
print(df.describe())

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    float64
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    float64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(4), int64(5)
memory usage: 54.1 KB
None
       Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  

In [27]:
features=[
    "Pregnancies",
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "Insulin",
    "BMI",
    "DiabetesPedigreeFunction",
    "Age"
]

X = df[features]

y = df["Outcome"]

print("Features:")
print(X.head())

print("\nTarget:")
print(y.head())

Features:
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148           72.0             35    169.5  33.6   
1            1       85           66.0             29    102.5  26.6   
2            8      183           64.0             32    169.5  23.3   
3            1       89           66.0             23     94.0  28.1   
4            0      137           40.0             35    168.0  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33  

Target:
0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64


In [9]:
print(X.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64


no missing valuess

---



In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)
print("training data",len(X_train))
print("testing data",len(X_test))

training data 614
testing data 154


In [11]:
#creating logistic regression model
model=LogisticRegression(max_iter=1000)
print(model)
LogisticRegression(max_iter=1000)

LogisticRegression(max_iter=1000)


LogisticRegression(max_iter=1000)

In [12]:
#training
model.fit(X_train,y_train)
print("model training completed")


model training completed


In [13]:
#predictions
y_pred=model.predict(X_test)
print("Prediction")
print(y_pred[:20])

Prediction
[0 0 0 0 0 1 0 0 1 1 0 1 1 0 0 0 0 0 1 0]


In [26]:
#accuracy
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy",accuracy)
print("Accuracy percentage",accuracy*100,"%")

Accuracy 0.7727272727272727
Accuracy percentage 77.27272727272727 %


In [15]:
#confusion matrix
CM=confusion_matrix(y_test,y_pred)
print("confusion matrix", "\n", CM)

confusion matrix 
 [[83 16]
 [19 36]]


In [16]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.84      0.83        99
           1       0.69      0.65      0.67        55

    accuracy                           0.77       154
   macro avg       0.75      0.75      0.75       154
weighted avg       0.77      0.77      0.77       154



In [22]:
probabilities=model.predict_proba(X_test)
print(probabilities[:10])

[[0.62825398 0.37174602]
 [0.84854063 0.15145937]
 [0.90674301 0.09325699]
 [0.84410519 0.15589481]
 [0.59756704 0.40243296]
 [0.49192119 0.50807881]
 [0.9880119  0.0119881 ]
 [0.70262586 0.29737414]
 [0.48652278 0.51347722]
 [0.33752325 0.66247675]]


In [18]:
new_patient = pd.DataFrame({
    "Pregnancies": [2],
    "Glucose": [120],
    "BloodPressure": [70],
    "SkinThickness": [25],
    "Insulin": [80],
    "BMI": [25.0],
    "DiabetesPedigreeFunction": [0.5],
    "Age": [30]
})

prediction = model.predict(new_patient)

probability = model.predict_proba(new_patient)

print("Prediction:", prediction)

print("Probability of NOT having diabetes:",
      probability[0][0])

print("Probability of having diabetes:",
      probability[0][1])

Prediction: [0]
Probability of NOT having diabetes: 0.8870590803869907
Probability of having diabetes: 0.11294091961300937


In [21]:
if prediction[0] == 1:
  print("predicts:diabetes")
else:
  print("predicts:no diabetes")

predicts:no diabetes


In [32]:
coefficients=pd.DataFrame({
    "features":features,
    "coefficients":model.coef_[0]
})
print(coefficients)

                   features  coefficients
0               Pregnancies      0.067035
1                   Glucose      0.031002
2             BloodPressure     -0.009791
3             SkinThickness      0.045226
4                   Insulin      0.004516
5                       BMI      0.064015
6  DiabetesPedigreeFunction      0.481401
7                       Age      0.033209
